### ISSUE TITLE
Can We relay on uuid as unique?

### ISSUE THREAD

**Issue by thmohd** [nicolewhite/neo4j-flask#10]
is uuid4 actually unique when we are dealing with ten thousands of nodes?

**Comment by nicolewhite** [comment]
Yes, it is [extremely unlikely](https://en.wikipedia.org/wiki/Universally_unique_identifier#Random_UUID_probability_of_duplicates) you will ever duplicate a UUID.

**Comment by thmohd** [comment]
Thank you.
